# Generated by Django 2.2.6 on 2019-10-10 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='hopes_newsletters',
            new_name='hopes_newsletter',
        ),
    ]
