# Generated by Django 2.2.6 on 2019-10-11 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20191010_1622'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_verified',
        ),
        migrations.AddField(
            model_name='user',
            name='date_verified',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date verified'),
        ),
    ]
