# Generated by Django 2.2.6 on 2019-11-01 05:38

import accounts.validators
import bookplaylist.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20191011_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='comment',
            field=bookplaylist.models.NullCharField(blank=True, max_length=50, null=True, verbose_name='comment'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=bookplaylist.models.NullEmailField(blank=True, error_messages={'unique': 'A user with that email address already exists.'}, help_text='Required. Enter a valid email address.', max_length=254, null=True, unique=True, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='facebook_id',
            field=bookplaylist.models.NullCharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Facebook ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=bookplaylist.models.NullCharField(blank=True, max_length=30, null=True, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=bookplaylist.models.NullCharField(blank=True, max_length=150, null=True, verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='twitter_id',
            field=bookplaylist.models.NullCharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Twitter ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=bookplaylist.models.NullCharField(blank=True, error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and _ only.', max_length=150, null=True, unique=True, validators=[accounts.validators.UnicodeUsernameValidator()], verbose_name='username'),
        ),
    ]
