# Generated by Django 2.2.6 on 2019-11-13 10:23

import bookplaylist.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20191101_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='comment',
            field=bookplaylist.models.NullTextField(blank=True, null=True, verbose_name='comment'),
        ),
    ]
