# Generated by Django 2.2.6 on 2019-11-30 03:01

import accounts.validators
import bookplaylist.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20191122_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=bookplaylist.models.fields.NullEmailField(blank=True, error_messages={'unique': 'A user with that email address already exists.'}, help_text='Required. Enter a valid email address.', max_length=254, null=True, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='facebook_id',
            field=bookplaylist.models.fields.NullCharField(blank=True, max_length=255, null=True, verbose_name='Facebook ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='twitter_id',
            field=bookplaylist.models.fields.NullCharField(blank=True, max_length=255, null=True, verbose_name='Twitter ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=bookplaylist.models.fields.NullCharField(blank=True, error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and _ only.', max_length=150, null=True, validators=[accounts.validators.UnicodeUsernameValidator()], verbose_name='username'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['username'], name='username'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='email'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('is_active', True)), fields=('username',), name='username'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('is_active', True)), fields=('email',), name='email'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('is_active', True)), fields=('twitter_id',), name='twitter_id'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('is_active', True)), fields=('facebook_id',), name='facebook_id'),
        ),
    ]
