# Generated by Django 2.2.6 on 2019-12-11 03:18

import accounts.validators
import bookplaylist.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_user_nickname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=bookplaylist.models.fields.NullEmailField(error_messages={'unique': 'A user with that email address already exists.'}, help_text='Required. Enter a valid email address.', max_length=254, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=bookplaylist.models.fields.NullCharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and _ only.', max_length=150, validators=[accounts.validators.UnicodeUsernameValidator()], verbose_name='username'),
        ),
    ]
