# Generated by Django 2.2.6 on 2019-12-11 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20191211_1218'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='user',
            name='twitter_id',
        ),
        migrations.RemoveConstraint(
            model_name='user',
            name='facebook_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='facebook_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='twitter_id',
        ),
    ]
