# Generated by Django 2.2.6 on 2019-12-13 07:12

import bookplaylist.models.utils
from django.db import migrations, models
import functools


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_auto_20191211_1326'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to=functools.partial(bookplaylist.models.utils.get_file_path, *(), **{'field': 'profile_image'}), verbose_name='Profile image'),
        ),
        migrations.RunSQL(
            "ALTER TABLE `users` MODIFY `profile_image` varchar(100) AFTER `comment`",
            migrations.RunSQL.noop,
        ),
    ]
