# Generated by Django 2.2.6 on 2019-12-13 07:12

import accounts.models.base
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_auto_20191211_1326'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to=accounts.models.base.get_profile_image_path, verbose_name='Profile image'),
        ),
        migrations.RunSQL(
            "ALTER TABLE `users` MODIFY `profile_image` varchar(100) AFTER `comment`",
            migrations.RunSQL.noop,
        ),
    ]
