# Generated by Django 2.2.6 on 2019-12-14 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_user_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='shows_twitter_link',
            field=models.BooleanField(default=True, verbose_name='showing twitter link in profile'),
        ),
        migrations.RunSQL(
            "ALTER TABLE `users` MODIFY `shows_twitter_link` bool DEFAULT b'1' NOT NULL AFTER `hopes_newsletter`",
            migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            "ALTER TABLE `users` ALTER COLUMN `shows_twitter_link` DROP DEFAULT",
            migrations.RunSQL.noop,
        ),
    ]
