# Generated by Django 2.2.6 on 2019-10-09 09:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('isbn', models.CharField(max_length=13, unique=True, verbose_name='ISBN')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('title_collation_key', models.CharField(blank=True, max_length=255, null=True, verbose_name='collation key')),
                ('volume', models.CharField(blank=True, max_length=50, null=True, verbose_name='volume')),
                ('series', models.CharField(blank=True, max_length=255, null=True, verbose_name='series')),
                ('publisher', models.CharField(blank=True, max_length=255, null=True, verbose_name='publisher')),
                ('pubdate', models.CharField(blank=True, max_length=10, null=True, verbose_name='publication date')),
                ('cover', models.URLField(blank=True, null=True, verbose_name='cover')),
                ('author', models.CharField(blank=True, max_length=255, null=True, verbose_name='author')),
                ('amazon_url', models.URLField(blank=True, null=True, verbose_name='Amazon URL')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'book',
                'verbose_name_plural': 'books',
                'db_table': 'books',
                'ordering': ['isbn'],
            },
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
                ('title', models.CharField(max_length=50, verbose_name='title')),
                ('description', models.TextField(verbose_name='description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'playlist',
                'verbose_name_plural': 'playlists',
                'db_table': 'playlists',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlaylistBook',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Playlist', verbose_name='playlist')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.Book', verbose_name='book')),
                ('description', models.TextField(verbose_name='description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'book in playlist',
                'verbose_name_plural': 'books in playlists',
                'db_table': 'playlists_books',
                'ordering': ['playlist', 'book'],
            },
        ),
        migrations.AddField(
            model_name='playlist',
            name='books',
            field=models.ManyToManyField(through='main.PlaylistBook', to='main.Book', verbose_name='books'),
        ),
        migrations.AddField(
            model_name='book',
            name='playlists',
            field=models.ManyToManyField(blank=True, through='main.PlaylistBook', to='main.Playlist', verbose_name='playlists'),
        ),
    ]
