# Generated by Django 2.2.6 on 2019-10-10 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['title'], name='title'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['publisher'], name='publisher'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['pubdate'], name='pubdate'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['author'], name='author'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['created_at'], name='created_at'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['updated_at'], name='updated_at'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['title', 'volume', 'series'], name='idx01'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['pubdate', 'title'], name='idx02'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['title', 'title_collation_key', 'author'], name='idx03'),
        ),
        migrations.AddIndex(
            model_name='playlist',
            index=models.Index(fields=['title'], name='title'),
        ),
        migrations.AddIndex(
            model_name='playlist',
            index=models.Index(fields=['created_at'], name='created_at'),
        ),
        migrations.AddIndex(
            model_name='playlist',
            index=models.Index(fields=['updated_at'], name='updated_at'),
        ),
        migrations.AddIndex(
            model_name='playlist',
            index=models.Index(fields=['user', 'created_at'], name='idx01'),
        ),
        migrations.AddIndex(
            model_name='playlistbook',
            index=models.Index(fields=['created_at'], name='created_at'),
        ),
        migrations.AddIndex(
            model_name='playlistbook',
            index=models.Index(fields=['updated_at'], name='updated_at'),
        ),
    ]
