# Generated by Django 2.2.6 on 2019-10-16 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20191016_1735'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.Category', verbose_name='category'),
        ),
        migrations.RunSQL(
            "ALTER TABLE `playlists` MODIFY `category_id` CHAR(32) NOT NULL AFTER `user_id`",
            migrations.RunSQL.noop,
        ),
    ]
