# Generated by Django 2.2.6 on 2019-10-16 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_playlist_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(verbose_name='slug'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['slug'], name='slug'),
        ),
        migrations.RunSQL(
            "ALTER TABLE `categories` MODIFY `slug` VARCHAR(50) NOT NULL AFTER `name`",
            migrations.RunSQL.noop,
        ),
    ]
