# Generated by Django 2.2.6 on 2019-10-16 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20191016_2240'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='category',
            name='slug',
        ),
    ]
