# Generated by Django 2.2.6 on 2019-10-31 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20191016_2333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='pubdate',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='book',
            name='volume',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='volume'),
        ),
    ]
