# Generated by Django 2.2.6 on 2019-11-01 02:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20191031_2324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlistbook',
            name='book',
            field=models.ForeignKey(db_column='book_isbn', on_delete=django.db.models.deletion.PROTECT, to='main.Book', to_field='isbn', verbose_name='book'),
        ),
    ]
