# Generated by Django 2.2.6 on 2019-11-01 05:38

import bookplaylist.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20191101_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='amazon_url',
            field=bookplaylist.models.NullURLField(blank=True, null=True, verbose_name='Amazon URL'),
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=bookplaylist.models.NullCharField(blank=True, max_length=255, null=True, verbose_name='author'),
        ),
        migrations.AlterField(
            model_name='book',
            name='cover',
            field=bookplaylist.models.NullURLField(blank=True, null=True, verbose_name='cover'),
        ),
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=bookplaylist.models.NullCharField(max_length=13, unique=True, verbose_name='ISBN'),
        ),
        migrations.AlterField(
            model_name='book',
            name='pubdate',
            field=bookplaylist.models.NullCharField(blank=True, max_length=255, null=True, verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='book',
            name='publisher',
            field=bookplaylist.models.NullCharField(blank=True, max_length=255, null=True, verbose_name='publisher'),
        ),
        migrations.AlterField(
            model_name='book',
            name='series',
            field=bookplaylist.models.NullCharField(blank=True, max_length=255, null=True, verbose_name='series'),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=bookplaylist.models.NullCharField(max_length=255, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='book',
            name='title_collation_key',
            field=bookplaylist.models.NullCharField(blank=True, max_length=255, null=True, verbose_name='collation key'),
        ),
        migrations.AlterField(
            model_name='book',
            name='volume',
            field=bookplaylist.models.NullCharField(blank=True, max_length=255, null=True, verbose_name='volume'),
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=bookplaylist.models.NullTextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=bookplaylist.models.NullCharField(max_length=50, unique=True, verbose_name='category name'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=bookplaylist.models.NullSlugField(unique=True, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='description',
            field=bookplaylist.models.NullTextField(verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='title',
            field=bookplaylist.models.NullCharField(max_length=50, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='playlistbook',
            name='description',
            field=bookplaylist.models.NullTextField(verbose_name='description'),
        ),
    ]
