# Generated by Django 2.2.6 on 2019-11-02 01:49

import bookplaylist.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20191101_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='title',
            field=bookplaylist.models.NullCharField(blank=True, max_length=255, null=True, verbose_name='title'),
        ),
    ]
