# Generated by Django 2.2.6 on 2019-11-17 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20191116_1154'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date deleted'),
        ),
        migrations.AddField(
            model_name='bookdata',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date deleted'),
        ),
        migrations.AddField(
            model_name='playlist',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date deleted'),
        ),
        migrations.AddField(
            model_name='playlistbook',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date deleted'),
        ),
        migrations.AddField(
            model_name='provider',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date deleted'),
        ),
        migrations.AddField(
            model_name='theme',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date deleted'),
        ),
    ]
