# Generated by Django 2.2.6 on 2019-11-17 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20191117_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookdata',
            name='book',
            field=models.ForeignKey(db_column='book_isbn', on_delete=django.db.models.deletion.CASCADE, related_name='book_data_set', related_query_name='book_data', to='main.Book', to_field='isbn', verbose_name='book'),
        ),
        migrations.AlterField(
            model_name='bookdata',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_data_set', related_query_name='book_data', to='main.Provider', verbose_name='provider'),
        ),
        migrations.AlterField(
            model_name='playlistbook',
            name='book',
            field=models.ForeignKey(db_column='book_isbn', on_delete=django.db.models.deletion.PROTECT, related_name='playlist_book_set', related_query_name='playlist_book', to='main.Book', to_field='isbn', verbose_name='book'),
        ),
        migrations.AlterField(
            model_name='playlistbook',
            name='playlist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlist_book_set', related_query_name='playlist_book', to='main.Playlist', verbose_name='playlist'),
        ),
    ]
