# Generated by Django 2.2.6 on 2019-11-17 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_auto_20191117_1947'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='playlistbook',
            unique_together={('playlist', 'book')},
        ),
    ]
