# Generated by Django 2.2.6 on 2019-11-22 06:48

import bookplaylist.models.utils
from django.db import migrations, models
import functools


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_auto_20191117_2207'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='card',
            field=models.ImageField(blank=True, null=True, upload_to=functools.partial(bookplaylist.models.utils.get_file_path, *(), **{'field': 'og_image'}), verbose_name='card'),
        ),
        migrations.RunSQL(
            "ALTER TABLE `playlists` MODIFY `card` varchar(100) AFTER `description`",
            migrations.RunSQL.noop,
        ),
    ]
