# Generated by Django 2.2.6 on 2019-11-25 03:50

import bookplaylist.models.utils
from django.db import migrations, models
import functools


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_playlist_card'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlist',
            name='card',
        ),
        migrations.AddField(
            model_name='playlist',
            name='og_image',
            field=models.ImageField(blank=True, null=True, upload_to=functools.partial(bookplaylist.models.utils.get_file_path, *(), **{'field': 'og_image'}), verbose_name='Open Graph image'),
        ),
        migrations.RunSQL(
            "ALTER TABLE `playlists` MODIFY `og_image` varchar(100) AFTER `description`",
            migrations.RunSQL.noop,
        ),
    ]
