# Generated by Django 2.2.6 on 2019-11-30 03:01

import bookplaylist.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_auto_20191125_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='priority',
            field=models.SmallIntegerField(verbose_name='priority'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='slug',
            field=bookplaylist.models.fields.NullSlugField(verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='name',
            field=bookplaylist.models.fields.NullCharField(max_length=50, verbose_name='theme name'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='slug',
            field=bookplaylist.models.fields.NullSlugField(blank=True, null=True, verbose_name='slug'),
        ),
        migrations.AlterUniqueTogether(
            name='bookdata',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='playlistbook',
            unique_together=set(),
        ),
        migrations.AddIndex(
            model_name='provider',
            index=models.Index(fields=['name'], name='name'),
        ),
        migrations.AddIndex(
            model_name='provider',
            index=models.Index(fields=['slug'], name='slug'),
        ),
        migrations.AddIndex(
            model_name='provider',
            index=models.Index(fields=['priority'], name='priority'),
        ),
        migrations.AddIndex(
            model_name='theme',
            index=models.Index(fields=['name'], name='name'),
        ),
        migrations.AddIndex(
            model_name='theme',
            index=models.Index(fields=['slug'], name='slug'),
        ),
        migrations.AddConstraint(
            model_name='provider',
            constraint=models.UniqueConstraint(condition=models.Q(deleted_at__isnull=True), fields=('name',), name='name'),
        ),
        migrations.AddConstraint(
            model_name='provider',
            constraint=models.UniqueConstraint(condition=models.Q(deleted_at__isnull=True), fields=('slug',), name='slug'),
        ),
        migrations.AddConstraint(
            model_name='provider',
            constraint=models.UniqueConstraint(condition=models.Q(deleted_at__isnull=True), fields=('priority',), name='priority'),
        ),
        migrations.AddConstraint(
            model_name='theme',
            constraint=models.UniqueConstraint(condition=models.Q(deleted_at__isnull=True), fields=('name',), name='name'),
        ),
        migrations.AddConstraint(
            model_name='theme',
            constraint=models.UniqueConstraint(condition=models.Q(deleted_at__isnull=True), fields=('slug',), name='slug'),
        ),
        migrations.AddConstraint(
            model_name='bookdata',
            constraint=models.UniqueConstraint(fields=('book', 'provider'), name='book_isbn_provider_id_uniq'),
        ),
        migrations.AddConstraint(
            model_name='playlistbook',
            constraint=models.UniqueConstraint(condition=models.Q(deleted_at__isnull=True), fields=('playlist', 'book'), name='playlist_id_book_isbn_uniq'),
        ),
    ]
