# Generated by Django 2.2.6 on 2019-12-16 04:49

import bookplaylist.models.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0022_auto_20191130_1201'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', related_query_name='like', to='main.Playlist', verbose_name='playlist')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', related_query_name='like', to=settings.AUTH_USER_MODEL, verbose_name='user')),
                ('message', bookplaylist.models.fields.NullTextField(blank=True, null=True, verbose_name='message')),
                ('date_notified', models.DateTimeField(blank=True, null=True, verbose_name='date notified')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='date updated')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='date deleted')),
            ],
            options={
                'verbose_name': 'like',
                'verbose_name_plural': 'likes',
                'db_table': 'likes',
                'ordering': ['playlist', 'created_at'],
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='like',
            index=models.Index(fields=['created_at'], name='created_at'),
        ),
        migrations.AddIndex(
            model_name='like',
            index=models.Index(fields=['updated_at'], name='updated_at'),
        ),
        migrations.AddIndex(
            model_name='like',
            index=models.Index(fields=['playlist', 'created_at'], name='idx01'),
        ),
        migrations.AddIndex(
            model_name='like',
            index=models.Index(fields=['user', 'created_at'], name='idx02'),
        ),
        migrations.AddIndex(
            model_name='like',
            index=models.Index(fields=['playlist', 'date_notified', 'created_at'], name='idx03'),
        ),
        migrations.AddConstraint(
            model_name='like',
            constraint=models.UniqueConstraint(condition=models.Q(deleted_at__isnull=True), fields=('playlist', 'user'), name='playlist_id_user_id_uniq'),
        ),
    ]
