# Generated by Django 2.2.6 on 2019-12-18 05:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0023_auto_20191216_1349'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='users_with_like',
            field=models.ManyToManyField(related_name='playlists_with_like', related_query_name='playlist_with_like', through='main.Like', to=settings.AUTH_USER_MODEL, verbose_name='Users with like'),
        ),
    ]
