# Generated by Django 2.2.6 on 2019-12-18 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_auto_20191216_1349'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='playlists',
        ),
        migrations.RemoveField(
            model_name='playlist',
            name='books',
        ),
    ]
