# Generated by Django 2.2.6 on 2019-12-19 07:16

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_auto_20191218_1738'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('playlist', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.Playlist', verbose_name='playlist')),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Theme', verbose_name='theme')),
                ('sequence', models.SmallIntegerField(verbose_name='sequence')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='date updated')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='date deleted')),
            ],
            options={
                'verbose_name': 'recommendation',
                'verbose_name_plural': 'recommendations',
                'db_table': 'recommendations',
                'ordering': ['theme', 'sequence'],
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='recommendation',
            index=models.Index(fields=['sequence'], name='sequence'),
        ),
        migrations.AddIndex(
            model_name='recommendation',
            index=models.Index(fields=['created_at'], name='created_at'),
        ),
        migrations.AddIndex(
            model_name='recommendation',
            index=models.Index(fields=['updated_at'], name='updated_at'),
        ),
        migrations.AddIndex(
            model_name='recommendation',
            index=models.Index(fields=['theme', 'sequence'], name='idx01'),
        ),
    ]
