# Generated by Django 2.2.6 on 2019-12-19 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_auto_20191219_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='sequence',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='sequence'),
        ),
        migrations.RunSQL(
            "ALTER TABLE `playlists` MODIFY `sequence` smallint AFTER `og_image`",
            migrations.RunSQL.noop,
        ),
        migrations.AddIndex(
            model_name='playlist',
            index=models.Index(fields=['sequence'], name='sequence'),
        ),
    ]
