# Generated by Django 2.2.6 on 2019-12-20 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_auto_20191220_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='sequence',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='sequence'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='priority',
            field=models.PositiveSmallIntegerField(verbose_name='priority'),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='sequence',
            field=models.PositiveSmallIntegerField(verbose_name='sequence'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='sequence',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='sequence'),
        ),
    ]
